### ISSUE TITLE
Some blades do not work on the anvil to enchant them

### ISSUE THREAD

**Issue by DankestO** [Truly-Modular/Arsenal#1]
I've been testing some blades, the rapier blade and longsword blade, they don't detect enchantments on the anvil, but if you go to an enchantment table you can enchant them.
I think it's just those two, unless I've skipped one without noticing.

![Captura de pantalla 2023-12-17 223141](https://github.com/Truly-Modular/Arsenal/assets/126206944/563a3569-1ded-4c76-8959-42ea58b875d0)

**Comment by Smartin-b** [comment]
sorry for the late response, this flew under my radar.
I cant replicate this issue on either fabric or forge? this could be a conflict with other mods, so a full modlist could be helpfull
![grafik](https://github.com/Truly-Modular/Arsenal/assets/67115074/5a8bfe9a-b701-40fe-aa90-e551a9194da4)

**Comment by Smartin-b** [comment]
Edit: after some further investiagtion this bug is a bit funny.
Generated Compat materials did set ALL materials as a possible repairmaterial, including Books, so they could nolonger be applied to undamaged items. 
Quick fix:
[Fabric jar](https://cdn.discordapp.com/attachments/1098169086275489823/1188752399830106112/Truly-Modular-miapi-1.1.3-1.20.1-snapshot-fabric.jar?ex=659baaf2&is=658935f2&hm=30046479d0ad093d20f90f45c337e17ed5c0725b71a5511c17705c85ae3bb609&)

[Forge jar](https://cdn.discordapp.com/attachments/1098169086275489823/1188752400102723624/Truly-Modular-miapi-1.1.3-1.20.1-snapshot-forge.jar?ex=659baaf2&is=658935f2&hm=682fb1712150c4984f4c944a27570b34d71a857530e4f4b7db4a37d8c5bc43ee&)

these jars should fix it, they also include some other fixes and changes, if any issues come up with them, please report them

**Comment by Smartin-b** [comment]
this is fixed in the latest public release now
